name: deploy_to_aks

on:
  workflow_call:
    inputs:
      aksName:
        required: true
        type: string
      resourceGroupName:
        required: true
        type: string
      containerRegistryUrl:
        required: true
        type: string
      githubSha:
        required: true
        type: string
      serviceAccount:
        required: true
        type: string
      managedIdentityClientId:
        required: true
        type: string
      akvName:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        name: Sign in to Azure
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group ${{ inputs.resourceGroupName }} --name ${{ inputs.aksName }}
      - name: replace_placeholders_with_current_run
        run: |
          find . -name kustomization.yaml -exec sed -i -e "s/<YOUR_ACR_SERVER>/${{ inputs.containerRegistryUrl }}/g" \
            -e "s/<YOUR_IMAGE_TAG>/${{ inputs.githubSha }}/g" \
            -e "s/<YOUR_SERVICE_ACCOUNT_NAME>/${{ inputs.serviceAccount }}/g" \
            -e "s/<YOUR_MANAGED_IDENTITY_CLIENT_ID>/${{ inputs.managedIdentityClientId }}/g" \
            -e "s/<YOUR_KEY_VAULT_NAME>/${{ inputs.akvName }}/g" \
            -e "s/<YOUR_TENANT_ID>/${{ secrets.AZURE_TENANT_ID }}/g" {} \;
        working-directory: ./manifests
      - name: Apply Kubernetes Configuration
        run: |
          kubectl apply -k ./manifests/overlays/dev/db
          sleep 60
          kubectl apply -k ./manifests/overlays/dev/api
          kubectl apply -k ./manifests/overlays/dev/web